### ISSUE TITLE
Error trying to create a new user

### ISSUE THREAD

**Issue by nizarelouaer** [PacktPublishing/Hands-On-Domain-Driven-Design-with-.NET#9]
I really enjoy the book and the examples but I am having an issue with the final project (Chapter13). I executed the code using the Visual Studio and I am having an error when I try to create a new user using the register form. Once I enter the user information and click "SIGNUP", the server returns the follwing error:
""
[10:48:01.988 DBG] () Marketplace.Users.UserProfiles.UserProfileCommandsApi Handling HTTP request of type "UserProfile"
[10:48:02.494 ERR] () Marketplace.Users.UserProfiles.UserProfileCommandsApi Error handling the command
System.NullReferenceException: Object reference not set to an instance of an object.
   at Marketplace.EventSourcing.ApplicationService`1.Handle[TCommand](TCommand command) in C:\work\T4ISB\.Net Core\DDD\Hands-On-Domain-Driven-Design-with-.NET-Core-master\Chapter13\src\Marketplace.EventSourcing\ApplicationService.cs:line 26
   at Marketplace.WebApi.CommandApi`1.HandleCommand[TCommand](TCommand command, Action`1 commandModifier) in C:\work\T4ISB\.Net Core\DDD\Hands-On-Domain-Driven-Design-with-.NET-Core-master\Chapter13\src\Marketplace.WebApi\CommandApi.cs:line 35
""

Thank you

**Comment by alexeyzimarev** [comment]
Thank you for the feedback. The Chapter 13 code is not final. I plan to finish everything (including changes in the chapter text) before Christmas.

**Comment by nizarelouaer** [comment]
Thank you for the reply. Do you plan to publish a chapter 13 ? The book has only 12 chapters and it will be great to have one more.

**Comment by alexeyzimarev** [comment]
I think it wasn't my decision. Packt decided to publish the chapter separately. But we are working on the errata collected since the book was published. When that's done, hopefully, the eBook will be updated.

**Comment by nizarelouaer** [comment]
Thank you Alexey. I am planning to read again your book, it is very rich and is helping me a lot in my project.

**Comment by alexeyzimarev** [comment]
The code for Chapter 13 deserves a bit more love. I promise to spend time cleaning it up.

**Comment by ghandmann** [comment]
Just in case, someone else stumbles upon this: The Password in the Sign-Up process for the Vue.js app provided by chapter 13 actually must be a valid UUID since it is used as the User-Id and not as a real "password". Found it out myself the hard way. ;)

@alexeyzimarev i think this "workaround" is fine. But it would be nice to document this somewhere (or did i just miss the hint somewhere?)

**Comment by alexeyzimarev** [comment]
You're absolutely right. I think the GUID format and the fact that it's a demo-style user id fetch is mentioned in Chapter 13.
